services:
  portfolio-app:
    build: ./app
    container_name: portfolio-app
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    depends_on:
      - portfolio-api

  portfolio-api:
    build: ./api
    container_name: portfolio-api
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"